"use client"
// import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { SchemaList } from "../../components/schema-list"
import { ThemeProvider } from "../../components/theme-provider"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ThemeProvider
					attribute="class"
					defaultTheme="dark"
					enableSystem
					disableTransitionOnChange
				>
					<div className="min-h-screen">
						<div className="flex">
							<aside className="w-64 bg-background border-r">
								<div className="p-4">
									<SchemaList
										onFileSelected={(name, from) =>
											console.log(
												`Loading file ${name} from ${from}...`,
											)
										}
									/>
								</div>
							</aside>
							<main className="flex-1 overflow-auto p-5">
								{children}
							</main>
						</div>
					</div>
				</ThemeProvider>
			</body>
		</html>
	)
}
