export enum ConnectFlags {
    CONNECT_NORMAL = 0,
    CONNECT_DEFERRED = 1,
    CONNECT_PERSIST = 2,
    CONNECT_ONE_SHOT = 4,
    CONNECT_REFERENCE_COUNTED = 8,
    CONNECT_APPEND_SOURCE_OBJECT = 16,
}